---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # To support conventional/angular commit style for Python Semantic
    commit-message:
      prefix: "deps"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # To support conventional/angular commit style for Python Semantic
    commit-message:
      prefix: "deps"
