---
name: Package Composite
description: Composite action to package and publish wheels
inputs:
  PyVersionLatest:
    description: Latest supported Python version
    required: true
  PkgRootFolder:
    description: root folder of Python package
    required: true
  OS:
    description: operating system
    required: true
runs:
  using: composite
  steps:
    - uses: "./.github/actions/steps_psr"
      name: Python Semantic Release
      with:
        PyVersionLatest: "${{inputs.PyVersionLatest}}"
        PkgRootFolder: "${{inputs.PkgRootFolder}}"
    - name: Install dependencies
      run: |-
        set -o errexit
        python -m pip install --upgrade pip
        pip install cibuildwheel uv
      shell: bash
    - name: Build wheels
      run: cibuildwheel --output-dir wheelhouse .
      shell: bash
      working-directory: "${{inputs.PkgRootFolder}}"
    - name: Publish Wheels for ${{inputs.OS}}
      uses: actions/upload-artifact@v4.1.0
      with:
        name: Wheels${{inputs.OS}}
        path: "${{inputs.PkgRootFolder}}/wheelhouse"
