---
name: Python Semantic Release Composite
description: Composite action to calculate semantic version through PSR
inputs:
  PyVersionLatest:
    description: Latest supported Python version
    required: true
  PkgRootFolder:
    description: root folder of Python package
    required: true
outputs:
  # https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
  pypi_released:
    description: "PyPI Released"
    value: ${{ steps.pythonsemanticrelease.outputs.released }}
  pypi_version:
    description: "PyPI Version"
    value: ${{ steps.pythonsemanticrelease.outputs.version }}
  pypi_tag:
    description: "PyPI Tag"
    value: ${{ steps.pythonsemanticrelease.outputs.tag }}
runs:
  using: composite
  steps:
    - name: Use Python ${{inputs.PyVersionLatest}}
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "${{inputs.PyVersionLatest}}"
        architecture: x64
    - name: PSR Setup
      # Pin to 8.* to not face regressions w/o knowing
      run: python -m pip install python-semantic-release==8.*
      working-directory: "${{inputs.PkgRootFolder}}"
      shell: bash
    - name: PSR Version
      id: pythonsemanticrelease
      working-directory: "${{inputs.PkgRootFolder}}"
      # PSR only used for setting the version number in setup.py and creating changelog
      # Everything else outsourced to other apps
      # See https://github.com/python-semantic-release/python-semantic-release/issues/589
      # Use static version in detached head (which in principle should only happen in PR)
      # Reason: https://github.com/python-semantic-release/python-semantic-release/issues/823
      run: |-
        if [[ "${{ github.event_name }}" != "pull_request" ]]
        then
          semantic-release -vv -c python-semantic-release.json version --changelog --no-commit --no-tag --no-push --no-vcs-release --skip-build
        else
          pip install . > /dev/null
          ver=$(python setup.py --version)
          echo "version=$ver" >> "$GITHUB_OUTPUT"
          echo "tag=v$ver" >> "$GITHUB_OUTPUT"
          echo "released=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
