---
name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    permissions:
      contents: read
    name: Build and Test
    uses: "./.github/workflows/build-reusable.yml"
    with:
      Pure: false
      PyVersionLatest: "3.13"
      # Relative to github.workspace
      PkgName: pylibCZIrw
      CIBWBEFOREALLLINUX: yum install -y glibc-static perl-IPC-Cmd
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  # Note: This job needs to stay outside a reusable workflow due to https://github.com/ZEISS/pylibczirw/issues/70
  upload:
    name: Deploy to PyPI
    permissions:
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    needs:
      - build
    # Needs to run on ubuntu
    runs-on: ubuntu-latest
    # If conditional based on https://github.com/actions/runner/issues/491#issuecomment-850884422
    if: |
      always() &&
      github.event_name != 'pull_request' &&
      needs.build.result == 'success' &&
      needs.build.outputs.pypi_released == 'true'
    environment:
      name: pypi
      url: https://pypi.org/project/pylibCZIrw/${{needs.build.outputs.pypi_version}}
    steps:
      - name: Download Wheels and Source Distribution
        uses: actions/download-artifact@v4.1.0
      - name: Collect Wheels and Source Distribution
        # Move to dist as default folder for publish action
        run: New-Item -Path "." -Name "dist" -ItemType "directory"; Get-ChildItem -Path ".\*.whl",".\*.tar.gz" -Recurse | Move-Item -Destination ".\dist"
        shell: pwsh
      - name: Upload to PyPI
        # As of 06/2024, trusted publishing does not work within reusable workflows located in a different repo
        # Tracked in:
        # https://github.com/pypa/gh-action-pypi-publish/issues/166
        # https://github.com/pypi/warehouse/issues/11096
        # https://docs.pypi.org/trusted-publishers/troubleshooting/#reusable-workflows-on-github
        # More info on trusted publishing: https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Basically runs twine check
          verify-metadata: true
  tag:
    permissions:
      contents: write
    needs:
      - build
      - upload
    # Aftermath of if-conditional of Upload job
    if: always() && needs.upload.result == 'success'
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Tag with PyPI version
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{needs.build.outputs.pypi_tag}}',
              sha: context.sha
            })
