---
name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
  contents: write
  # IMPORTANT: this permission is mandatory for trusted publishing
  id-token: write
jobs:
  build-test-deploy:
    name: Build, Test, Deploy to PyPI
    uses: "./.github/workflows/build-reusable.yml"
    with:
      Pure: false
      PyVersionLatest: "3.11"
      # Relative to github.workspace
      PySourceFolder: "pylibCZIrw"
      PkgName: pylibCZIrw
      CIBWBEFOREALLLINUX: yum install -y glibc-static perl-IPC-Cmd
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
