---
name: "Lint PR"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: read
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Needs to match types specified in python-semantic-release.json and CONTRIBUTING.md
          types: |
            chore
            docs
            feat
            fix
            perf
            refactor
            test
            deps
          requireScope: false
